server:
  port: 8083

spring:
  jackson:
    #配置json 处理时忽略空值
    default-property-inclusion: non_null
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.138.128:9300
  application:
    name: search-service
  main:
    #允许注册相同服务名
    allow-bean-definition-overriding: true

#注册中心
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8888/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

#日志级别
logging:
  level:
    com.cwh:  debug
  file:
    name: b2c-searchs-service.log
