server:
  port: 8083

spring:
  #整合rabbitmq
  rabbitmq:
    virtual-host: b2c
    host: 192.168.138.128
    username: b2c
    password: b2c
    #开启手动ack
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    #配置json 处理时忽略空值
    default-property-inclusion: non_null
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.138.128:9300
  application:
    name: search-service
  main:
    #允许注册相同服务名
    allow-bean-definition-overriding: true

#注册中心
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8888/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

#日志级别
logging:
  level:
    com.cwh:  debug
  file:
    name: b2c-searchs-service.log

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms
feign.hystrix.enabled: true
