spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: upload-service
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8888/eureka
  instance:
    #十秒内没收到心跳则过期
    lease-expiration-duration-in-seconds: 10
    #每间隔五秒发送一次心跳
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

#分布式文件服务配置
fdfs:
  # 链接超时
  connect-timeout: 60
  # 读取时间
  so-timeout: 60
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  tracker-list: 192.168.138.128:22122
#  tracker-list: 140.143.231.47:22122

logging:
  level:
    com.cwh:  debug
  file:
    name: b2c-upload-service.log

#图片上传域名
image:
  server: http://image.b2c.com/
